services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - cutlink-network
    restart: always
    volumes:
      - redis-data:/data

networks:
  cutlink-network:
    driver: bridge

volumes:
  redis-data:
